### ISSUE TITLE
Lego-Container can't start on EV3

### ISSUE THREAD

**Issue by kinnder** [gseteamproject/smartfactory#17]
Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14                                                                                        2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by kinnder** [comment]
https://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi

**Comment by kinnder** [comment]
[ERROR] Failed to execute goal on project lego-container: Could not resolve dependencies for project smartfactory:lego-container:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at smartfactory:core:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for smartfactory:core:jar:0.0.1-SNAPSHOT: Could not find artifact smartfactory:smartfactory:pom:0.0.1-SNAPSHOT in central (http://central.maven.org/maven2/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by kinnder** [comment]
Java Runtime on EV3 doesn't support logj4-library as it requires Java 6
